server:
  port: 12000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #http://127.0.0.1:12000/main/user-dev.yml
          uri: https://github.com/lijunzhuo/spring_cloud_configuration.git
#          #搜索目录
#          search-paths:
#            - spring_cloud_configuration
#      #读取分支
#      label: main

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
